# This file wont do us much good in this location, make sure you change the path as directed to continue!

name: Docker CD

on:
  push:
    paths:
      - "**Dockerfile**"
jobs:      
  Build-and-Push-Docker-Image:
      runs-on: ubuntu-latest
#      needs: test
      name: Docker Build, Tag, Push

 #     steps:
 #     - name: Checkout
 #       uses: actions/checkout@v1
 #     - name: Download built artifact
 #       uses: actions/download-artifact@main
 #       with:
 #         name: webpack artifacts
 #         path: public
 #     - name: Build container image
 #       uses: docker/build-push-action@v1
 #       with:
 #         username: ${{github.actor}}
 #         password: ${{secrets.GITHUB_TOKEN}}
 #         registry: docker.pkg.github.com
 #         repository: thesegoto11/github-actions-for-packages/tic-tac-toe
 #         tag_with_sha: true
          
      steps:
        -
          name: Checkout code
          uses: actions/checkout@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            platforms: linux/arm/v7
#            pull: true
            push: true
#            build-args: |
#              arg1=value1
#              arg2=value2
#            cache-from: type=registry,ref=myorg/myrepository:latest
#            cache-to: type=inline
            tags: ghcr.io/thesegoto11/github-actions-for-packages/tic-tac-toe:latest
